### ISSUE TITLE
improved completions with type hinting

### ISSUE THREAD

**Issue by willwhitney** [jupyter/jupyter_client#19] opened 2015-05-17 02:14 UTC
The `autocomplete-plus` package for the Atom editor (recently bundled into Atom) shows how powerful [types in autocomplete](https://github.com/atom/autocomplete-plus/pull/334) can be.

![atom completions](https://cloud.githubusercontent.com/assets/69169/6793515/b505ee3a-d182-11e4-9b9f-74b2a5d77365.png)

Something similar would be a huge boon to Jupyter. Instead of just showing text matches for variables in the running kernel (already very powerful!), show what they are: a variable of type String, a function that takes two integers and returns a float, etc. 

This would be a huge step forward for interactive programming of interpreted languages, and would truly showcase the power of having a live kernel to introspect into.

**Comment by Carreau** [comment] 2015-05-17 02:21
We have been planning completion refactor [for a while](https://github.com/ipython/ipython/wiki/IPEP-11%3A-Tab-Completion-System-Refactor), we just don't get the bandwidth to do it, but if you want to have a shot at it, or maybe help to describe what we can learn from atom to do it later, that would be great.

**Comment by Carreau** [comment] 2015-05-17 02:23
Duplicate of jupyter/notebook#99 , Closing, please don't post issues twice.

**Closed by Carreau** 2015-05-17 02:23 UTC

**Comment by willwhitney** [comment] 2015-05-17 02:25
Sorry, wasn't sure which was the right place! I might get motivated and
take on this refactor.

**Comment by Carreau** [comment] 2015-05-17 03:43
> Sorry, wasn't sure which was the right place

No problem, either is fine, the border is blurry, we are just mostly the same person on all repo and after people get confused and post on both issues,  I'll lock this specific issue to prevent any edit on this issue to keep 2 different threads from being spawned.

We are always happy to get new contributor, feel free to ask for question. Completion is a complex subject so you might need some guidance.
