### ISSUE TITLE
BlockingKernelClient.execute will hang sometimes

### ISSUE THREAD

**Issue by daliagachc** [jupyter/jupyter_client#545] opened 2020-04-27 23:11 UTC
when i run the following snippet from a notebook, it executes successfully 'most of the time', but approx 1 out of 5 times, it will end up with the kernel freezing 

```python
import jupyter_client
km=jupyter_client.BlockingKernelClient()
km.load_connection_info(kernel_dic)
res = km.execute('a=3')
```

**Comment by MSeal** [comment] 2020-04-27 23:34
What version of jupyter_client are you running? Is this using ipython kernel (that version is important too) and are you on Python 3.6+?

If you're trying to do notebook execution specifically -- https://nbclient.readthedocs.io/en/latest/ is a better tool for that ontop of jupyter_client (some people don't know that exists).

**Comment by daliagachc** [comment] 2020-04-28 01:57
hi! thanks for the reply! 
im running jupyter_client 6.1.3, python 3.7. and ipython 7.13.0. 
I think that nbclient wont do what im trying to do: 
modify variable values in a notebook that is open and being used. Basically i want to communicate with this notebook from another notebook.

**Comment by daliagachc** [comment] 2020-04-28 02:04
However if I use AsyncKernelClient instead of BlockingKernelClient it works as expected and the response seems to by immediate (at least i cant notice any delay)
```python
import jupyter_client
km=jupyter_client.AsyncKernelClient()
km.load_connection_info(kernel_dic)
res = km.execute('a=3')
```

**Comment by MSeal** [comment] 2020-04-28 04:52
Hmm. It seems to only hang when run from inside a Notebook for me. Making a generic python script to execute the blocking client code is not hanging. That implies there's some socket conflict going in the zmq layer since that's the shared interface with the Notebook. Does this only occur for you as well when run in a notebook?

**Comment by davidbrochart** [comment] 2020-04-28 08:11
I can reproduce in the notebook and in the python prompt (python and ipython). It hangs because we never receive the `execute_reply` message. I also confirm that `AsyncKernelClient` never hangs.

**Comment by davidbrochart** [comment] 2020-04-28 08:47
With the following code it doesn't seem to hang but the kernel takes a huge amount of memory and CPU:
```python
import jupyter_client
km=jupyter_client.KernelManager()
km.start_kernel()
kc = km.client()
kc.start_channels()
kc.wait_for_ready()
res = kc.execute('a=3')
```

**Comment by davidbrochart** [comment] 2020-04-28 10:01
I think the CPU and memory consumption were caused by some debug leftover on my side.
@daliagachc you should use the sequence above.

**Comment by daliagachc** [comment] 2020-04-28 10:19
Thanks @davidbrochart! My only concern is that i dont start the kernels myself. they are created in the notebook that im communicating with. Is there any indication against using AsynKernelClient? Also, on an off topic, is there anyway i can run a cell on the "tethered" notebook?

**Comment by davidbrochart** [comment] 2020-04-28 10:33
Maybe the issue comes from the way the kernels are started in the notebook. Do they wait for the kernel to be ready?
You can use an `AsyncKernelClient` but which client class is used when the kernel is started? The way to change that later on is:
```python
km.client_class = 'jupyter_client.asynchronous.AsyncKernelClient'
```
Then, if you want to run cells it's better to just use nbclient, as @MSeal pointed out.

**Comment by MSeal** [comment] 2020-04-28 17:00
Good points @davidbrochart . Also @daliagachc I would also be hesitant to have multiple notebooks applications speaking to the same live kernel. You'll be increasing the amount of implicit execution and assumptions while potentially reducing visibility with the notebook tools available in jupyter. It might make perfect sense for what you're trying to do, but I thought I'd point out the potential visibility issues.

**Comment by davidbrochart** [comment] 2020-05-18 08:23
@daliagachc should we close this issue?

**Comment by daliagachc** [comment] 2020-05-18 09:12
Yes! thank you for the help. I ended up using the AsyncKernelClient and it works well. I basically wanted to activate/deactivate buttons in notebook 'A' from notebook 'B'. I think that it works well.

**Closed** 2020-05-18 09:17 UTC
