### ISSUE TITLE
List kernelspec in connection file

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyter_client#52] opened 2015-07-17 21:24 UTC
For any frontend that uses a connection file on the side (only sidecar to my knowledge), it would be helpful if the connection file listed the name of the kernelspec associated with that running kernel (as it does on the `/api/kernels` endpoint).

Otherwise, a developer has to make a `kernel_info_request` (even if they didn't need the `SHELL` socket) or do some tricky file descriptor -> pid nonsense.

**Comment by minrk** [comment] 2015-07-17 22:40
`jupyter kernels list` analogue of `jupyter kernelspec list`?

**Comment by minrk** [comment] 2015-07-17 22:41
oh, sorry. Just re-read and now understand what you mean. Ignore previous comment.

Yes, I think this is easy enough to do, and helpful for connection-file consumers.

**Comment by rgbkrk** [comment] 2015-07-18 00:57
Yeah, exactly what we talked about at Medici's. I posted it to have it down.

**Comment by minrk** [comment] 2015-10-05 08:09
Just noticed that this is a duplicate of #50, two issues prior.

**Closed by minrk** 2015-10-05 08:09 UTC

**Comment by rgbkrk** [comment] 2015-10-05 13:56
Only 5 days apart!
